---
name: WWW-Scraper-ISBN-AmazonDE_Driver
version: 0.01
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: "Search driver for the (DE) Amazon online\ncatalog."
license: perl
requires:
  WWW::Scraper::ISBN: 0
  WWW::Scraper::ISBN::Driver: 0
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  WWW::Scraper::ISBN::AmazonDE_Driver:
    file: lib/WWW/Scraper/ISBN/AmazonDE_Driver.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
