---
name: WWW-Scraper-ISBN-AmazonDE_Driver
version: 0.03
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: Search driver for the (DE) Amazon online catalog.
license: perl
requires:
  WWW::Mechanize: 1.2
  WWW::Scraper::ISBN: 0.24
  WWW::Scraper::ISBN::Driver: 0.17
  Web::Scraper: 0.13
build_requires:
  Test::More: 0
  WWW::Mechanize: 1.2
  WWW::Scraper::ISBN: 0.24
  WWW::Scraper::ISBN::Driver: 0.17
  Web::Scraper: 0.13
provides:
  WWW::Scraper::ISBN::AmazonDE_Driver:
    file: lib/WWW/Scraper/ISBN/AmazonDE_Driver.pm
    version: 0.03
generated_by: Module::Build version 0.26
